services:
  fastapi-app:
    build:
      context: .
    #ports:
    #  - 8000:8000
    volumes:
      - ./src:/app
    
  nginx:
    image: nginx:1.27.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
